### ISSUE TITLE
liststreamitems pagination does not work for descending ordering

### ISSUE THREAD

**Issue by nflaig** [MultiChain/multichain#123]
It is currently not possible to have pagination for descending ordering of `liststreamitems ` which is a common cause, for example if you have an audit trail you want to display the newest entries when you load it. The problem is there is no way to know which start value to use if the total item count is not known.

Since ascending ordering is working because the start value 1 can be used a good solution would be to add a new parameter `order` were `ascending` or `descending` could be provided and then for `descending` the start value of 1 would be the newest entry instead of the oldest.

**Comment by titusz** [comment]
You can implement descending ordering based on the existing API. As an example see:  https://github.com/coblo/mex/blob/master/mex/stream.py#L7

**Comment by nflaig** [comment]
@titusz thanks for the answer, do you also know it it is possible to get the total count of the entries?
