### ISSUE TITLE
"-initprivkey" broken with 2.1.1

### ISSUE THREAD

**Issue by phmarek** [MultiChain/multichain#127]
I've got a private key; starting multichain 2.0.7 with `-initprivkey=V...` works, but 2.1.1 rejects the same commandline with

```
Error: Cannot set initial private key: Invalid private key encoding
```

**Comment by gidgreen** [comment]
Is this the same blockchain , or at least same relevant blockchain parameters? Private keys are formatted in a chain-specific way.

**Comment by phmarek** [comment]
I can't reproduce it any more, so that might have been the problem.
Sorry about the noise.
