### ISSUE TITLE
"-rpcport" not honored in "params.dat"

### ISSUE THREAD

**Issue by phmarek** [MultiChain/multichain#128]
When connecting a multichain instance to another one via `multichaind <chain>@<server>:<bcport> -rpcport=<rpcport>`, `rpcport` is correctly used for RPC - but `<bcport> - 1` is put in `params.dat`.

Seems that a wrong default value is used for the file; that means processes parsing that file (or a restarted daemon) use the wrong port.

This is with 2.1.1.

**Comment by gidgreen** [comment]
The `params.dat` file contains blockchain default parameters, and is unaffected by runtime parameters. (In general, we recommend posting questions like this on the Q&A.)

**Comment by phmarek** [comment]
Hi Gideon,

thanks for the answer!

If it were *only* *default* parameters and not related to the actual active blockchain at all, then why write it out on a connecting node?

The blockchain (`net`) port is correctly written to `params.dat`, just the RPC port is "guessed" instead of taken in from the command line; I still believe for consistencies' sake it should be either both or none, preferably both, of course.

**Comment by gidgreen** [comment]
The `params.dat` contains the blockchain parameters. It is not node-specific in any way. Part of this definition is the default port for RPC. If you start your node without the `rpcport` parameter this is what will be used.
