### ISSUE TITLE
nValue of CTxOut only holding 0 when at CreateNewBlock

### ISSUE THREAD

**Issue by neilc1** [MultiChain/multichain#15]
Poking around with the debugger at CreateNewBlock. It seems that the nValue of all the CTxOuts taken from tx.vin and tx.vout are set to 0. For a quick check you can run the current tx's GetValueOut and it will report 0. I had to recompile with O0 in order to verify this. I recommend taking a look, as this would lead to a lot of weird behavior, like the transaction fee not being set properly. CCoinsViewCache is relaying that the txin does have coins, so I suspect the issue isn't far away. Although when accessing a given txin's previous output's vout, the nValue is also empty (src/miner/miner.cpp L418-L422)

**Comment by gidgreen** [comment]
By default MultiChain blockchains don't use a native currency, so the nValue should be zero.

**Comment by neilc1** [comment]
Gotcha, thanks for clarifying.
