### ISSUE TITLE
liststreamitems doesn't work on windows 10?

### ISSUE THREAD

**Issue by luzi41** [MultiChain/multichain#17]
I receive only an empty array when calling 'multichain-cli.exe testchain liststreamitems "test-stream" false'. liststreamitems on my linux machine works without problems. Is this a general problem on windows?

**Comment by SimplyUb** [comment]
On Windows 7 with Multichain in version alpha 24, the twice are working :

multichain-cli.exe ChainTest liststreamitems test01 false
and
multichain-cli.exe ChainTest liststreamitems "test01" false

which version of MultiChain do you use ?

**Comment by luzi41** [comment]
I use the Multichain Windows 1.0 Beta 2. I just updated from Beta 1. I've downloaded the binaries for windows. I'll try to build another version from source (alpha 24). 
I have also tried with and without quotes.

**Comment by luzi41** [comment]
I've tried the new beta 2 on a fresh Windows 7: No problems with liststreamitems.. I'll try again on a new windows 10 vm.

**Comment by luzi41** [comment]
On a fresh Windows 10 VM liststreamitems works without problem :-). I'll try to discover the real problem on my first Windows 10 machine.
