### ISSUE TITLE
Blockchain parameter `minimum-per-output` is ignored

### ISSUE THREAD

**Issue by titusz** [MultiChain/multichain#27]
On a test chain based on the latest release version (1.0.1) of multichain I was able to create and confirm a 1 raw unit native currency transaction without transaction fee while the blockchain parameters are set to:
`minimum-per-output = 10000`
`minimum-relay-fee = 10000`

Maybe I am doing something wrong but it seems to be a bug.

**Comment by gidgreen** [comment]
Thanks - we're taking a look.

**Comment by gidgreen** [comment]
We've identified this bug and a fix will be rolled into 1.0.2. (If you're wondering how this wasn't caught until now, the vast majority of MultiChain usage and testing has focused on chains without a native currency.)

**Comment by gidgreen** [comment]
This should be fixed in 1.0.2.
