### ISSUE TITLE
Simplify Running Two Nodes on One Machine

### ISSUE THREAD

**Issue by lazaridiscom** [MultiChain/multichain#43]
Right within the Getting Started (https://www.multichain.com/getting-started/) I hit on a problem.

After looking up for a solution, I found this here:

https://www.multichain.com/qa/2817/how-to-run-datadir-in-multichain

This is far too complicated (for a getting-started) and should be drastically simplified. The first contact with MultiChain should be smooth and barrier-free.

Is there any way (without code-level changes) to replace the need of the many cmd-line parameters (`-datadir=.multichain-other -port=10255 -rpcport=10254), e.g. running the tools from within different installation-dirs or similar?

**Comment by gidgreen** [comment]
You can put the `port` and `rpcport` parameters inside the `multichain.conf` file in the appropriate `datadir` then you don't need to put them on the command line. But in any event you should note these instructions are only for the unusual situation where you are running multiple nodes on a single computer.

**Comment by lazaridiscom** [comment]
[You should not close issues that fast]

>only for the unusual situation where you are running multiple nodes on a single computer.

The "unusual situation" is not that unusual. I downloaded MultiChain in order to evaluate it, and hit immediately on a quite misleading documentation and the **very inconvenient** way of running two nodes on one machine.

Newcomers and evaluators will always hit on this barriers. Are you not interested to remove it?
