### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by ccebrecos** [MultiChain/multichain#59]
Hello,
I've created a new local environment with a stream in order to publish some documents, not so large (200K). The steps are:

```
xxd -p pre.pdf | tr -d '\n' > pre.hex
var=$(cat pre.hex)
multichain-cli testenv publish documents pdf $var
```
And i'm getting the following error:

`/usr/local/bin/multichain-cli: The argument list is too long`

There's any way to avoid that error ?  

*ps: It works fine for the first 2184 lines of the xxd output.*

**Comment by gidgreen** [comment]
This will be a limitation of your shell environment rather than MultiChain. You may need to access the JSON-RPC API directly rather than via the `multichain-cli` wrapper. (FYI the next alpha of MultiChain 2.0 will provide an alternative mechanism for getting large chunks of data into a stream item.)

**Comment by ccebrecos** [comment]
Using the JSON-RPC API via python (just a few lines) I cant just publish ~230300 bytes, which represents the 35.05% of the pdf in hex..

**Comment by ccebrecos** [comment]
With fewer bytes it returns the txid as expected, but with more it returns `None`.

To make the request I've used the file in hex transformed as I mentioned before with `xxd `and the [python code](https://github.com/ccebrecos/py-telegram-bot/blob/master/src/rpc/rpc.py) I had to interact with the bitcoin-core, with a couple of modifications..

**Comment by gidgreen** [comment]
It sounds like you're still passing the parameter on the command-line and still coming up against the same command-line limit. You need to have the Python code obtain the data itself, not be passed it as a parameter.

**Comment by ccebrecos** [comment]
When converting the file to hex, i've putted a '\n' at the end, that made the hex chars to be odd and the error was: 
`{u'id': 1, u'result': None, u'error': {u'message': u'Item data should be hexadecimal string', u'code': -8}}`

So i tested without the '\n' at the end with python and it worked, my mistake!

Thanks for the replies ! :smile:
