### ISSUE TITLE
Unable to create and sign 3-to-4 multisig.

### ISSUE THREAD

**Issue by amithanamakkanavar** [MultiChain/multichain#6]
created 3-to-4 multisig using
addmultisigaddress 3 '["02d819390343b71d8a354f874e9d7e2274fa29dfd53ce32927bc7701aa355535da", "0253b1a5b5f4448dcaa1d20955dd14822aac7cef605fb67b4ed755717efd157d53", "03e09aad2dbe87a56ff8c3508b13f2be3eb55b81eeb6e2e0ccc75702de702e046c", "03d2dc053d833c03007d395bf45dccbb578d1e711726f07f3ea72e6252f625d2e6"]'
but when I try to sign any transaction  ' "complete" : false ' is shown for all sign from 4 nodes.

**Comment by gidgreen** [comment]
Thanks but please post these kinds of questions on the Q&A:

http://www.multichain.com/qa/
