### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by maektwain** [MultiChain/multichain#7]
OS Mac OS X 10.12.13
While building 
1st error 
Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)

resolved using installing 

```brew install berkeley@4```

2nd error 
OpenSSL ec header missing

resolved using 

```export LDFLAGS=-L/usr/local/opt/openssl/lib```

```export CPPFLAGS=-I/usr/local/opt/openssl/include```

**Comment by gidgreen** [comment]
Thanks – this is really helpful. After that could you get it to bulid?

**Comment by maektwain** [comment]
No I did the other way round using docker ubuntu machine and running a script inside and using volumes to do changes in the source code.

I am still working on the DEPS which are being used in MAC 

While its time consuming but i will try this week.

Thanks

**Comment by gidgreen** [comment]
FYI we already have a working Mac OS X build and are also working on reducing its dependencies. So you should have something from us within a few weeks.

**Comment by maektwain** [comment]
That Works Great
